name: Gradle Build

on:
  push:
    paths:
      - 'app/*'
      - 'common/*'
      - '*.gradle'
  pull_request:
    paths:
      - 'app/*'
      - 'common/*'
      - '*.gradle'

jobs:
  test:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: set up JDK 1.8
        uses: actions/setup-java@master
        with:
          java-version: 1.8
      - name: Build with Gradle
        run: ./gradlew test
